version: "3.9"

services:
    app-web:
        container_name: ${HTTP_SERVER_NAME}
        build: .
        ports:
            - ${HTTP_SERVER_PORT}:8080
        depends_on:
            - db
        command: ./wait-db.sh db "./pkk"
        environment:
            ENV: ${ENV}
            POSTGRES_USER: ${DB_USER_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    db:
        restart: always
        container_name: ${DB_NAME}
        image: postgres
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./.database/postgres/data:/var/lib/postgresql/data