// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	models "ZeroAgencyTest/internal/service/news_service/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetNews provides a mock function with given fields: ctx
func (_m *Service) GetNews(ctx context.Context) ([]models.News, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNews")
	}

	var r0 []models.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.News, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.News); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNews provides a mock function with given fields: ctx, news
func (_m *Service) UpdateNews(ctx context.Context, news models.News) error {
	ret := _m.Called(ctx, news)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.News) error); ok {
		r0 = rf(ctx, news)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
